version: "3.7"
services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APPLICATION_NAME}.wordpress
    image: ${APPLICATION_NAME}/wordpress:${APPLICATION_TAG}
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
